#!/bin/sh
# From QiuSimons

cd /overlay
rm -rf `ls | egrep -v '(upper|.fs_state)'`
cd upper
rm -rf `ls | egrep -v '(etc)'`
cd etc/config
rm -rf `ls | egrep '(luci|ucitrack)'`
cd ..
rm -rf `ls | egrep -v '(config|chinadns-ng|samba|smartdns|ssr|bench.log|passwd|shadow|luci-wrtbwmon.conf|sysupgrade.conf)'`
sleep 5 && touch /etc/banner && reboot